[build]
builder = "nixpacks"
watchPatterns = ["backend/**"]

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["...", "ffmpeg"]
