import { notFound } from "next/navigation";
import { Suspense } from "react";
import Link from "next/link";
import { getReport, staticUrl } from "../../../../lib/api";
import { ReportHeader } from "../../../components/ReportHeader";
import { FindingsPanel } from "../../../components/FindingsPanel";
import { TranscriptViewer } from "../../../components/TranscriptViewer";
import { OsintMatches } from "../../../components/OsintMatches";
import { VideoTimeline } from "../../../components/VideoTimeline";
import { HeatmapViewer } from "../../../components/HeatmapViewer";
import type { Metadata } from "next";

// SSR — fetch at request time
export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const resolvedParams = await params;
  return {
    title: `Forensic Report ${resolvedParams.id.slice(0, 8)} — DeepVerify`,
    description: "Video authenticity forensic report generated by DeepVerify",
  };
}

async function ReportPage({ params }: PageProps) {
  const { id } = await params;

  let report;
  try {
    report = await getReport(id);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : "Unknown error";
    // If still processing, show a refreshable waiting page
    if (msg.includes("in progress") || msg.includes("202")) {
      return (
        <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", background: "var(--bg-base)" }}>
          <div style={{ textAlign: "center", padding: "40px" }}>
            <div style={{ fontSize: "3rem", marginBottom: "16px" }}>⏳</div>
            <h1 style={{ fontSize: "1.3rem", fontWeight: 700, color: "var(--text-primary)", margin: "0 0 8px" }}>
              Analysis In Progress
            </h1>
            <p style={{ color: "var(--text-muted)", marginBottom: "24px" }}>
              Job <code style={{ fontFamily: "JetBrains Mono, monospace", fontSize: "0.85rem" }}>{id}</code> is still processing.
            </p>
            <div style={{ display: "flex", gap: "12px", justifyContent: "center" }}>
              <a href={`/report/${id}`} style={{
                padding: "10px 20px", borderRadius: "var(--radius-md)",
                background: "linear-gradient(135deg, var(--indigo-600), #7c3aed)",
                color: "#fff", fontWeight: 700, textDecoration: "none", fontSize: "0.875rem",
              }}>
                Refresh Page
              </a>
              <Link href="/" style={{
                padding: "10px 20px", borderRadius: "var(--radius-md)",
                border: "1px solid var(--border)", color: "var(--text-secondary)",
                fontWeight: 600, textDecoration: "none", fontSize: "0.875rem",
              }}>
                Back to Home
              </Link>
            </div>
          </div>
        </div>
      );
    }
    // Hard error
    return notFound();
  }

  const { verdict, audio, vision, osint, video_meta } = report;

  // Build video URL
  const videoUrl = video_meta.video_path
    ? (() => {
        try {
          const rel = video_meta.video_path.replace(/^\/tmp\//, "");
          return `${process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000"}/static/${rel}`;
        } catch {
          return null;
        }
      })()
    : null;

  // Build suspicious frames for HeatmapViewer with public URLs
  const suspiciousFrames = vision.suspicious_frames.map((f) => ({
    timestamp: f.timestamp,
    manipulation_score: f.manipulation_score,
    gradcam_path: f.gradcam_path
      ? (() => {
          try {
            const rel = f.gradcam_path!.replace(/^\/tmp\//, "");
            return `${process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000"}/static/${rel}`;
          } catch { return null; }
        })()
      : null,
    frame_path: (() => {
      try {
        const rel = f.frame_path.replace(/^\/tmp\//, "");
        return `${process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000"}/static/${rel}`;
      } catch { return f.frame_path; }
    })(),
  }));

  return (
    <div style={{ minHeight: "100vh", background: "var(--bg-surface)" }}>
      {/* Nav */}
      <nav style={{
        position: "sticky", top: 0, zIndex: 10,
        background: "rgba(255,255,255,0.9)", backdropFilter: "blur(12px)",
        borderBottom: "1px solid var(--border)",
        padding: "0 32px",
        display: "flex", alignItems: "center", justifyContent: "space-between",
        height: "60px",
      }}>
        <Link href="/" style={{
          display: "flex", alignItems: "center", gap: "10px", textDecoration: "none",
        }}>
          <div style={{
            width: "32px", height: "32px", borderRadius: "var(--radius-md)",
            background: "linear-gradient(135deg, var(--indigo-600), #7c3aed)",
            display: "flex", alignItems: "center", justifyContent: "center", fontSize: "1rem",
          }}>
            🔍
          </div>
          <span style={{ fontWeight: 800, fontSize: "1rem", color: "var(--text-primary)" }}>
            Deep<span style={{
              background: "linear-gradient(135deg, var(--indigo-600), #7c3aed)",
              WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent",
            }}>Verify</span>
          </span>
        </Link>
        <span style={{
          fontSize: "0.8rem", color: "var(--text-muted)",
          fontFamily: "JetBrains Mono, monospace",
          background: "var(--bg-subtle)", padding: "4px 12px",
          borderRadius: "999px", border: "1px solid var(--border)",
        }}>
          Report #{id.slice(0, 8)}
        </span>
      </nav>

      {/* Main content */}
      <main style={{ maxWidth: "1100px", margin: "0 auto", padding: "32px 24px 80px" }}>
        {/* Report header */}
        <div className="animate-fade-in-up" style={{ marginBottom: "24px" }}>
          <ReportHeader verdict={verdict} jobId={id} />
        </div>

        {/* Two-column layout */}
        <div style={{
          display: "grid",
          gridTemplateColumns: "minmax(0,1.4fr) minmax(0,1fr)",
          gap: "20px",
          alignItems: "start",
        }}>
          {/* Left column */}
          <div style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
            {/* Video player */}
            {videoUrl && (
              <div className="animate-fade-in-up" style={{ animationDelay: "0.05s" }}>
                <VideoTimeline
                  videoPath={videoUrl}
                  events={verdict.timeline_events}
                  duration={video_meta.duration_seconds}
                />
              </div>
            )}

            {/* Heatmap viewer */}
            <div className="animate-fade-in-up" style={{ animationDelay: "0.1s" }}>
              <HeatmapViewer
                suspiciousFrames={suspiciousFrames}
                timelineEvents={verdict.timeline_events}
              />
            </div>

            {/* Transcript */}
            <div className="animate-fade-in-up" style={{ animationDelay: "0.15s" }}>
              <TranscriptViewer audio={audio} />
            </div>

            {/* OSINT */}
            <div className="animate-fade-in-up" style={{ animationDelay: "0.2s" }}>
              <OsintMatches osint={osint} />
            </div>
          </div>

          {/* Right column — sticky findings */}
          <div style={{ position: "sticky", top: "76px" }}>
            <div className="animate-fade-in-up" style={{ animationDelay: "0.05s" }}>
              <FindingsPanel verdict={verdict} vision={vision} />
            </div>
          </div>
        </div>

        {/* Footer */}
        <div style={{
          marginTop: "40px", textAlign: "center",
          padding: "20px", borderTop: "1px solid var(--border)",
        }}>
          <p style={{ color: "var(--text-muted)", fontSize: "0.8rem" }}>
            Forensic analysis powered by C2PA · EfficientNet-B4 · Groq Whisper · SerpApi · GPT-4o-mini
            &nbsp;·&nbsp;
            <Link href="/" style={{ color: "var(--indigo-600)", fontWeight: 600, textDecoration: "none" }}>
              Analyze another video →
            </Link>
          </p>
        </div>
      </main>
    </div>
  );
}

export default function Page({ params }: PageProps) {
  return (
    <Suspense fallback={
      <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center" }}>
        <div style={{ fontSize: "0.875rem", color: "var(--text-muted)" }}>Loading report...</div>
      </div>
    }>
      <ReportPage params={params} />
    </Suspense>
  );
}
